title: KELDA
description: your source to open source
theme: jekyll-theme-minimal
logo: /assets/img/fountain.png
exclude: [Dockerfile, LICENSE, README.md, vendor, .bundle, old_training]
collections:
  training_specifics:
    output: true
    permalink: /training_specfics/:path/
defaults: